# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
